name: build
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-node@v1
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build