name: build
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build